Modified users so that the attributes doesn't change when adding an authority.
CSC207-UofT/course-project-codemonkeys pull request #46
Opened 2021-11-24 06:34 UTC by Vim0315

To do this, I added setter and getter for UUID in the Identifiable class. Is this okay?
The corresponding tests are added and passed.
I have also added some proper java doc to entity classes, more will be added in the future.
Sorry for the long pull request, it was too late when I realized.

2021-11-24 18:13 UTC, tammyliuu commented on src/test/java/Users/AdminTest.java
>  }
Looking good so far.

2021-11-25 00:01 UTC, langsonzhang commented
Looks good. But I have one question: why do we need to set() the UUID? I don't see a scenario where we would need to change the UUID of an object. Also, this causes a big problem since we hash using the UUID, and we rely on the fact that it does not change once initialized. So overall, I think we should keep UUID as a private final instance. Note that the UUID itself is an immutable class, so you cannot change it even if you have direct access using get().

2021-11-25 00:02 UTC, langsonzhang commented on src/main/java/Identification/Identifiable.java
> +    public UUID id;
Should be final. This allows misuse via hashing.

2021-11-25 00:03 UTC, langsonzhang commented on src/main/java/Identification/Identifiable.java
> +    public void setId(UUID id) {
Same idea. Changing the UUID will cause problems.

2021-11-25 00:05 UTC, langsonzhang requested changes

2021-11-25 00:05 UTC, langsonzhang commented on src/main/java/Identification/Identifiable.java
>  public abstract class Identifiable {
getId() is a good addition. But I think others should not be added.

2021-11-25 01:36 UTC, closed without merging